# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31f07a201b13ffacd9c23c03a7dfbb0e"
name = "product_lister"
handle = "product_lister-1"
application_url = "https://laden-alabama-convergence-psychology.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "urmilaapr17.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://laden-alabama-convergence-psychology.trycloudflare.com/auth/callback",
  "https://laden-alabama-convergence-psychology.trycloudflare.com/auth/shopify/callback",
  "https://laden-alabama-convergence-psychology.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
